{"resultsPerPage":13,"startIndex":0,"totalResults":13,"format":"NVD_CVE","version":"2.0","timestamp":"2024-11-18T02:55:46.970","vulnerabilities":[{"cve":{"id":"CVE-2024-52867","sourceIdentifier":"cve@mitre.org","published":"2024-11-17T03:15:04.003","lastModified":"2024-11-17T03:15:04.003","vulnStatus":"Received","cveTags":[],"descriptions":[{"lang":"en","value":"guix-daemon in GNU Guix before 5ab3c4c allows privilege escalation because build outputs are accessible by local users before file metadata concerns (e.g., for setuid and setgid programs) are properly addressed. The vulnerability can be remediated within the product via certain pull, reconfigure, and restart actions. Both 5ab3c4c and 5582241 are needed to resolve the vulnerability."}],"metrics":{"cvssMetricV31":[{"source":"cve@mitre.org","type":"Secondary","cvssData":{"version":"3.1","vectorString":"CVSS:3.1\/AV:L\/AC:H\/PR:N\/UI:N\/S:C\/C:H\/I:H\/A:H","attackVector":"LOCAL","attackComplexity":"HIGH","privilegesRequired":"NONE","userInteraction":"NONE","scope":"CHANGED","confidentialityImpact":"HIGH","integrityImpact":"HIGH","availabilityImpact":"HIGH","baseScore":8.1,"baseSeverity":"HIGH"},"exploitabilityScore":1.4,"impactScore":6.0}]},"references":[{"url":"https:\/\/git.savannah.gnu.org\/cgit\/guix.git\/commit\/?id=558224140dab669cabdaebabff18504a066c48d4","source":"cve@mitre.org"},{"url":"https:\/\/git.savannah.gnu.org\/cgit\/guix.git\/commit\/?id=5ab3c4c1e43ebb637551223791db0ea3519986e1","source":"cve@mitre.org"},{"url":"https:\/\/guix.gnu.org\/en\/blog\/2024\/build-user-takeover-vulnerability\/","source":"cve@mitre.org"}]}},{"cve":{"id":"CVE-2024-52871","sourceIdentifier":"cve@mitre.org","published":"2024-11-17T04:15:03.973","lastModified":"2024-11-17T04:15:03.973","vulnStatus":"Received","cveTags":[],"descriptions":[{"lang":"en","value":"In Flagsmith before 2.134.1, it is possible to bypass the ALLOW_REGISTRATION_WITHOUT_INVITE setting."}],"metrics":{},"references":[{"url":"https:\/\/github.com\/Flagsmith\/flagsmith\/compare\/v2.134.0...v2.134.1","source":"cve@mitre.org"},{"url":"https:\/\/github.com\/Flagsmith\/flagsmith\/pull\/4454","source":"cve@mitre.org"}]}},{"cve":{"id":"CVE-2024-52872","sourceIdentifier":"cve@mitre.org","published":"2024-11-17T04:15:04.047","lastModified":"2024-11-17T04:15:04.047","vulnStatus":"Received","cveTags":[],"descriptions":[{"lang":"en","value":"In Flagsmith before 2.134.1, the get_document endpoint is not correctly protected by permissions."}],"metrics":{},"references":[{"url":"https:\/\/github.com\/Flagsmith\/flagsmith\/compare\/v2.134.0...v2.134.1","source":"cve@mitre.org"},{"url":"https:\/\/github.com\/Flagsmith\/flagsmith\/pull\/4459","source":"cve@mitre.org"}]}},{"cve":{"id":"CVE-2024-52876","sourceIdentifier":"cve@mitre.org","published":"2024-11-17T05:15:04.760","lastModified":"2024-11-17T05:15:04.760","vulnStatus":"Received","cveTags":[],"descriptions":[{"lang":"en","value":"Holy Stone Remote ID Module HSRID01, firmware distributed with the Drone Go2 mobile application before 1.1.8, allows unauthenticated \"remote power off\" actions (in broadcast mode) via multiple read operations on the ASTM Remote ID (0xFFFA) GATT."}],"metrics":{},"references":[{"url":"https:\/\/coalfire.com\/the-coalfire-blog\/holy-stone-remote-id-vulnerability-disclosure","source":"cve@mitre.org"}]}},{"cve":{"id":"CVE-2020-25720","sourceIdentifier":"secalert@redhat.com","published":"2024-11-17T11:15:04.320","lastModified":"2024-11-17T11:15:04.320","vulnStatus":"Received","cveTags":[],"descriptions":[{"lang":"en","value":"A vulnerability was found in Samba where a delegated administrator with permission to create objects in Active Directory can write to all attributes of the newly created object, including security-sensitive attributes, even after the object's creation. This issue occurs because the administrator owns the object due to the lack of an Access Control List (ACL) at the time of creation and later being recognized as the 'creator owner.' The retained significant rights of the delegated administrator may not be well understood, potentially leading to unintended privilege escalation or security risks."}],"metrics":{"cvssMetricV31":[{"source":"secalert@redhat.com","type":"Primary","cvssData":{"version":"3.1","vectorString":"CVSS:3.1\/AV:N\/AC:H\/PR:L\/UI:N\/S:U\/C:H\/I:H\/A:H","attackVector":"NETWORK","attackComplexity":"HIGH","privilegesRequired":"LOW","userInteraction":"NONE","scope":"UNCHANGED","confidentialityImpact":"HIGH","integrityImpact":"HIGH","availabilityImpact":"HIGH","baseScore":7.5,"baseSeverity":"HIGH"},"exploitabilityScore":1.6,"impactScore":5.9}]},"weaknesses":[{"source":"secalert@redhat.com","type":"Primary","description":[{"lang":"en","value":"CWE-264"}]}],"references":[{"url":"https:\/\/access.redhat.com\/security\/cve\/CVE-2020-25720","source":"secalert@redhat.com"},{"url":"https:\/\/bugzilla.redhat.com\/show_bug.cgi?id=2305954","source":"secalert@redhat.com"}]}},{"cve":{"id":"CVE-2023-0657","sourceIdentifier":"secalert@redhat.com","published":"2024-11-17T11:15:05.300","lastModified":"2024-11-17T11:15:05.300","vulnStatus":"Received","cveTags":[],"descriptions":[{"lang":"en","value":"A flaw was found in Keycloak. This issue occurs due to improperly enforcing token types when validating signatures locally. This could allow an authenticated attacker to exchange a logout token for an access token and possibly gain access to data outside of enforced permissions."}],"metrics":{"cvssMetricV31":[{"source":"secalert@redhat.com","type":"Primary","cvssData":{"version":"3.1","vectorString":"CVSS:3.1\/AV:A\/AC:H\/PR:L\/UI:R\/S:U\/C:L\/I:L\/A:N","attackVector":"ADJACENT_NETWORK","attackComplexity":"HIGH","privilegesRequired":"LOW","userInteraction":"REQUIRED","scope":"UNCHANGED","confidentialityImpact":"LOW","integrityImpact":"LOW","availabilityImpact":"NONE","baseScore":3.4,"baseSeverity":"LOW"},"exploitabilityScore":0.9,"impactScore":2.5}]},"weaknesses":[{"source":"secalert@redhat.com","type":"Primary","description":[{"lang":"en","value":"CWE-273"}]}],"references":[{"url":"https:\/\/access.redhat.com\/errata\/RHSA-2024:1867","source":"secalert@redhat.com"},{"url":"https:\/\/access.redhat.com\/errata\/RHSA-2024:1868","source":"secalert@redhat.com"},{"url":"https:\/\/access.redhat.com\/security\/cve\/CVE-2023-0657","source":"secalert@redhat.com"},{"url":"https:\/\/bugzilla.redhat.com\/show_bug.cgi?id=2166728","source":"secalert@redhat.com"}]}},{"cve":{"id":"CVE-2023-1419","sourceIdentifier":"secalert@redhat.com","published":"2024-11-17T11:15:05.593","lastModified":"2024-11-17T11:15:05.593","vulnStatus":"Received","cveTags":[],"descriptions":[{"lang":"en","value":"A script injection vulnerability was found in the Debezium database connector, where it does not properly sanitize some parameters. This flaw allows an attacker to send a malicious request to inject a parameter that may allow the viewing of unauthorized data."}],"metrics":{"cvssMetricV31":[{"source":"secalert@redhat.com","type":"Primary","cvssData":{"version":"3.1","vectorString":"CVSS:3.1\/AV:N\/AC:H\/PR:N\/UI:N\/S:U\/C:H\/I:N\/A:N","attackVector":"NETWORK","attackComplexity":"HIGH","privilegesRequired":"NONE","userInteraction":"NONE","scope":"UNCHANGED","confidentialityImpact":"HIGH","integrityImpact":"NONE","availabilityImpact":"NONE","baseScore":5.9,"baseSeverity":"MEDIUM"},"exploitabilityScore":2.2,"impactScore":3.6}]},"weaknesses":[{"source":"secalert@redhat.com","type":"Primary","description":[{"lang":"en","value":"CWE-233"}]}],"references":[{"url":"https:\/\/access.redhat.com\/security\/cve\/CVE-2023-1419","source":"secalert@redhat.com"},{"url":"https:\/\/bugzilla.redhat.com\/show_bug.cgi?id=2178722","source":"secalert@redhat.com"}]}},{"cve":{"id":"CVE-2023-4639","sourceIdentifier":"secalert@redhat.com","published":"2024-11-17T11:15:05.840","lastModified":"2024-11-17T11:15:05.840","vulnStatus":"Received","cveTags":[],"descriptions":[{"lang":"en","value":"A flaw was found in Undertow, which incorrectly parses cookies with certain value-delimiting characters in incoming requests. This issue could allow an attacker to construct a cookie value to exfiltrate HttpOnly cookie values or spoof arbitrary additional cookie values, leading to unauthorized data access or modification. The main threat from this flaw impacts data confidentiality and integrity."}],"metrics":{"cvssMetricV31":[{"source":"secalert@redhat.com","type":"Primary","cvssData":{"version":"3.1","vectorString":"CVSS:3.1\/AV:N\/AC:H\/PR:N\/UI:N\/S:U\/C:H\/I:H\/A:N","attackVector":"NETWORK","attackComplexity":"HIGH","privilegesRequired":"NONE","userInteraction":"NONE","scope":"UNCHANGED","confidentialityImpact":"HIGH","integrityImpact":"HIGH","availabilityImpact":"NONE","baseScore":7.4,"baseSeverity":"HIGH"},"exploitabilityScore":2.2,"impactScore":5.2}]},"weaknesses":[{"source":"secalert@redhat.com","type":"Primary","description":[{"lang":"en","value":"CWE-444"}]}],"references":[{"url":"https:\/\/access.redhat.com\/errata\/RHSA-2024:1674","source":"secalert@redhat.com"},{"url":"https:\/\/access.redhat.com\/errata\/RHSA-2024:1675","source":"secalert@redhat.com"},{"url":"https:\/\/access.redhat.com\/errata\/RHSA-2024:1676","source":"secalert@redhat.com"},{"url":"https:\/\/access.redhat.com\/errata\/RHSA-2024:1677","source":"secalert@redhat.com"},{"url":"https:\/\/access.redhat.com\/errata\/RHSA-2024:2763","source":"secalert@redhat.com"},{"url":"https:\/\/access.redhat.com\/errata\/RHSA-2024:2764","source":"secalert@redhat.com"},{"url":"https:\/\/access.redhat.com\/errata\/RHSA-2024:3919","source":"secalert@redhat.com"},{"url":"https:\/\/access.redhat.com\/security\/cve\/CVE-2023-4639","source":"secalert@redhat.com"},{"url":"https:\/\/bugzilla.redhat.com\/show_bug.cgi?id=2166022","source":"secalert@redhat.com"}]}},{"cve":{"id":"CVE-2023-6110","sourceIdentifier":"secalert@redhat.com","published":"2024-11-17T11:15:06.097","lastModified":"2024-11-17T11:15:06.097","vulnStatus":"Received","cveTags":[],"descriptions":[{"lang":"en","value":"A flaw was found in OpenStack. When a user tries to delete a non-existing access rule in it's scope, it deletes other existing access rules which are not associated with any application credentials."}],"metrics":{"cvssMetricV31":[{"source":"secalert@redhat.com","type":"Primary","cvssData":{"version":"3.1","vectorString":"CVSS:3.1\/AV:N\/AC:L\/PR:L\/UI:R\/S:U\/C:L\/I:L\/A:L","attackVector":"NETWORK","attackComplexity":"LOW","privilegesRequired":"LOW","userInteraction":"REQUIRED","scope":"UNCHANGED","confidentialityImpact":"LOW","integrityImpact":"LOW","availabilityImpact":"LOW","baseScore":5.5,"baseSeverity":"MEDIUM"},"exploitabilityScore":2.1,"impactScore":3.4}]},"references":[{"url":"https:\/\/access.redhat.com\/errata\/RHSA-2024:2737","source":"secalert@redhat.com"},{"url":"https:\/\/access.redhat.com\/errata\/RHSA-2024:2769","source":"secalert@redhat.com"},{"url":"https:\/\/access.redhat.com\/security\/cve\/CVE-2023-6110","source":"secalert@redhat.com"},{"url":"https:\/\/bugzilla.redhat.com\/show_bug.cgi?id=2212960","source":"secalert@redhat.com"},{"url":"https:\/\/code.engineering.redhat.com\/gerrit\/gitweb?p=python-openstackclient.git;a=commit;h=7a7c364bdd7b2cd2b56e73724110710a68d58abf","source":"secalert@redhat.com"},{"url":"https:\/\/review.opendev.org\/c\/openstack\/python-openstackclient\/+\/888697","source":"secalert@redhat.com"}]}},{"cve":{"id":"CVE-2024-0793","sourceIdentifier":"secalert@redhat.com","published":"2024-11-17T11:15:06.340","lastModified":"2024-11-17T11:15:06.340","vulnStatus":"Received","cveTags":[],"descriptions":[{"lang":"en","value":"A flaw was found in kube-controller-manager. This issue occurs when the initial application of a HPA config YAML lacking a .spec.behavior.scaleUp block causes a denial of service due to KCM pods going into restart churn."}],"metrics":{"cvssMetricV31":[{"source":"secalert@redhat.com","type":"Primary","cvssData":{"version":"3.1","vectorString":"CVSS:3.1\/AV:N\/AC:L\/PR:L\/UI:N\/S:C\/C:N\/I:N\/A:H","attackVector":"NETWORK","attackComplexity":"LOW","privilegesRequired":"LOW","userInteraction":"NONE","scope":"CHANGED","confidentialityImpact":"NONE","integrityImpact":"NONE","availabilityImpact":"HIGH","baseScore":7.7,"baseSeverity":"HIGH"},"exploitabilityScore":3.1,"impactScore":4.0}]},"weaknesses":[{"source":"secalert@redhat.com","type":"Primary","description":[{"lang":"en","value":"CWE-20"}]}],"references":[{"url":"https:\/\/access.redhat.com\/errata\/RHSA-2024:0741","source":"secalert@redhat.com"},{"url":"https:\/\/access.redhat.com\/errata\/RHSA-2024:1267","source":"secalert@redhat.com"},{"url":"https:\/\/access.redhat.com\/security\/cve\/CVE-2024-0793","source":"secalert@redhat.com"},{"url":"https:\/\/bugzilla.redhat.com\/show_bug.cgi?id=2214402","source":"secalert@redhat.com"},{"url":"https:\/\/github.com\/openshift\/kubernetes\/pull\/1876","source":"secalert@redhat.com"}]}},{"cve":{"id":"CVE-2023-43091","sourceIdentifier":"patrick@puiterwijk.org","published":"2024-11-17T13:15:14.140","lastModified":"2024-11-17T13:15:14.140","vulnStatus":"Received","cveTags":[],"descriptions":[{"lang":"en","value":"A flaw was found in GNOME Maps, which is vulnerable to a code injection attack via its service.json configuration file. If the configuration file is malicious, it may execute arbitrary code."}],"metrics":{"cvssMetricV31":[{"source":"patrick@puiterwijk.org","type":"Secondary","cvssData":{"version":"3.1","vectorString":"CVSS:3.1\/AV:N\/AC:L\/PR:N\/UI:N\/S:U\/C:H\/I:H\/A:H","attackVector":"NETWORK","attackComplexity":"LOW","privilegesRequired":"NONE","userInteraction":"NONE","scope":"UNCHANGED","confidentialityImpact":"HIGH","integrityImpact":"HIGH","availabilityImpact":"HIGH","baseScore":9.8,"baseSeverity":"CRITICAL"},"exploitabilityScore":3.9,"impactScore":5.9}]},"weaknesses":[{"source":"patrick@puiterwijk.org","type":"Secondary","description":[{"lang":"en","value":"CWE-79"}]}],"references":[{"url":"https:\/\/bugzilla.redhat.com\/show_bug.cgi?id=2239091","source":"patrick@puiterwijk.org"},{"url":"https:\/\/gitlab.gnome.org\/GNOME\/gnome-maps\/-\/commit\/d26cd774d524404ef7784e6808f551de83de4bea","source":"patrick@puiterwijk.org"},{"url":"https:\/\/gitlab.gnome.org\/GNOME\/gnome-maps\/-\/issues\/588","source":"patrick@puiterwijk.org"}]}},{"cve":{"id":"CVE-2024-11305","sourceIdentifier":"cna@vuldb.com","published":"2024-11-18T01:15:16.307","lastModified":"2024-11-18T01:15:16.307","vulnStatus":"Received","cveTags":[],"descriptions":[{"lang":"en","value":"A vulnerability classified as critical was found in Altenergy Power Control Software up to 20241108. This vulnerability affects the function get_status_zigbee of the file \/index.php\/display\/status_zigbee. The manipulation of the argument date leads to sql injection. The attack can be initiated remotely. The exploit has been disclosed to the public and may be used. The vendor was contacted early about this disclosure but did not respond in any way."}],"metrics":{"cvssMetricV40":[{"source":"cna@vuldb.com","type":"Secondary","cvssData":{"version":"4.0","vectorString":"CVSS:4.0\/AV:N\/AC:L\/AT:N\/PR:L\/UI:N\/VC:L\/VI:L\/VA:L\/SC:N\/SI:N\/SA:N\/E:X\/CR:X\/IR:X\/AR:X\/MAV:X\/MAC:X\/MAT:X\/MPR:X\/MUI:X\/MVC:X\/MVI:X\/MVA:X\/MSC:X\/MSI:X\/MSA:X\/S:X\/AU:X\/R:X\/V:X\/RE:X\/U:X","attackVector":"NETWORK","attackComplexity":"LOW","attackRequirements":"NONE","privilegesRequired":"LOW","userInteraction":"NONE","vulnerableSystemConfidentiality":"LOW","vulnerableSystemIntegrity":"LOW","vulnerableSystemAvailability":"LOW","subsequentSystemConfidentiality":"NONE","subsequentSystemIntegrity":"NONE","subsequentSystemAvailability":"NONE","exploitMaturity":"NOT_DEFINED","confidentialityRequirements":"NOT_DEFINED","integrityRequirements":"NOT_DEFINED","availabilityRequirements":"NOT_DEFINED","modifiedAttackVector":"NOT_DEFINED","modifiedAttackComplexity":"NOT_DEFINED","modifiedAttackRequirements":"NOT_DEFINED","modifiedPrivilegesRequired":"NOT_DEFINED","modifiedUserInteraction":"NOT_DEFINED","modifiedVulnerableSystemConfidentiality":"NOT_DEFINED","modifiedVulnerableSystemIntegrity":"NOT_DEFINED","modifiedVulnerableSystemAvailability":"NOT_DEFINED","modifiedSubsequentSystemConfidentiality":"NOT_DEFINED","modifiedSubsequentSystemIntegrity":"NOT_DEFINED","modifiedSubsequentSystemAvailability":"NOT_DEFINED","safety":"NOT_DEFINED","automatable":"NOT_DEFINED","recovery":"NOT_DEFINED","valueDensity":"NOT_DEFINED","vulnerabilityResponseEffort":"NOT_DEFINED","providerUrgency":"NOT_DEFINED","baseScore":5.3,"baseSeverity":"MEDIUM"}}],"cvssMetricV31":[{"source":"cna@vuldb.com","type":"Secondary","cvssData":{"version":"3.1","vectorString":"CVSS:3.1\/AV:N\/AC:L\/PR:L\/UI:N\/S:U\/C:L\/I:L\/A:L","attackVector":"NETWORK","attackComplexity":"LOW","privilegesRequired":"LOW","userInteraction":"NONE","scope":"UNCHANGED","confidentialityImpact":"LOW","integrityImpact":"LOW","availabilityImpact":"LOW","baseScore":6.3,"baseSeverity":"MEDIUM"},"exploitabilityScore":2.8,"impactScore":3.4}],"cvssMetricV2":[{"source":"cna@vuldb.com","type":"Secondary","cvssData":{"version":"2.0","vectorString":"AV:N\/AC:L\/Au:S\/C:P\/I:P\/A:P","accessVector":"NETWORK","accessComplexity":"LOW","authentication":"SINGLE","confidentialityImpact":"PARTIAL","integrityImpact":"PARTIAL","availabilityImpact":"PARTIAL","baseScore":6.5},"baseSeverity":"MEDIUM","exploitabilityScore":8.0,"impactScore":6.4,"acInsufInfo":false,"obtainAllPrivilege":false,"obtainUserPrivilege":false,"obtainOtherPrivilege":false,"userInteractionRequired":false}]},"weaknesses":[{"source":"cna@vuldb.com","type":"Primary","description":[{"lang":"en","value":"CWE-74"},{"lang":"en","value":"CWE-89"}]}],"references":[{"url":"https:\/\/github.com\/h0e4a0r1t\/h0e4a0r1t.github.io\/blob\/master\/2024\/HYO%3BY)v%3B4%5C)jLCjp\/Altenergy%20has%20a%20SQL%20injection%20vulnerability_status_zigbee.pdf","source":"cna@vuldb.com"},{"url":"https:\/\/vuldb.com\/?ctiid.284914","source":"cna@vuldb.com"},{"url":"https:\/\/vuldb.com\/?id.284914","source":"cna@vuldb.com"},{"url":"https:\/\/vuldb.com\/?submit.439800","source":"cna@vuldb.com"}]}},{"cve":{"id":"CVE-2024-11306","sourceIdentifier":"cna@vuldb.com","published":"2024-11-18T02:15:15.577","lastModified":"2024-11-18T02:15:15.577","vulnStatus":"Received","cveTags":[],"descriptions":[{"lang":"en","value":"A vulnerability, which was classified as critical, has been found in Altenergy Power Control Software up to 20241108. This issue affects some unknown processing of the file \/index.php\/display\/database\/. The manipulation leads to improper authorization. The attack may be initiated remotely. The exploit has been disclosed to the public and may be used. Other endpoints might be affected as well. The vendor was contacted early about this disclosure but did not respond in any way."}],"metrics":{"cvssMetricV40":[{"source":"cna@vuldb.com","type":"Secondary","cvssData":{"version":"4.0","vectorString":"CVSS:4.0\/AV:N\/AC:L\/AT:N\/PR:N\/UI:N\/VC:L\/VI:N\/VA:N\/SC:N\/SI:N\/SA:N\/E:X\/CR:X\/IR:X\/AR:X\/MAV:X\/MAC:X\/MAT:X\/MPR:X\/MUI:X\/MVC:X\/MVI:X\/MVA:X\/MSC:X\/MSI:X\/MSA:X\/S:X\/AU:X\/R:X\/V:X\/RE:X\/U:X","attackVector":"NETWORK","attackComplexity":"LOW","attackRequirements":"NONE","privilegesRequired":"NONE","userInteraction":"NONE","vulnerableSystemConfidentiality":"LOW","vulnerableSystemIntegrity":"NONE","vulnerableSystemAvailability":"NONE","subsequentSystemConfidentiality":"NONE","subsequentSystemIntegrity":"NONE","subsequentSystemAvailability":"NONE","exploitMaturity":"NOT_DEFINED","confidentialityRequirements":"NOT_DEFINED","integrityRequirements":"NOT_DEFINED","availabilityRequirements":"NOT_DEFINED","modifiedAttackVector":"NOT_DEFINED","modifiedAttackComplexity":"NOT_DEFINED","modifiedAttackRequirements":"NOT_DEFINED","modifiedPrivilegesRequired":"NOT_DEFINED","modifiedUserInteraction":"NOT_DEFINED","modifiedVulnerableSystemConfidentiality":"NOT_DEFINED","modifiedVulnerableSystemIntegrity":"NOT_DEFINED","modifiedVulnerableSystemAvailability":"NOT_DEFINED","modifiedSubsequentSystemConfidentiality":"NOT_DEFINED","modifiedSubsequentSystemIntegrity":"NOT_DEFINED","modifiedSubsequentSystemAvailability":"NOT_DEFINED","safety":"NOT_DEFINED","automatable":"NOT_DEFINED","recovery":"NOT_DEFINED","valueDensity":"NOT_DEFINED","vulnerabilityResponseEffort":"NOT_DEFINED","providerUrgency":"NOT_DEFINED","baseScore":6.9,"baseSeverity":"MEDIUM"}}],"cvssMetricV31":[{"source":"cna@vuldb.com","type":"Secondary","cvssData":{"version":"3.1","vectorString":"CVSS:3.1\/AV:N\/AC:L\/PR:N\/UI:N\/S:U\/C:L\/I:N\/A:N","attackVector":"NETWORK","attackComplexity":"LOW","privilegesRequired":"NONE","userInteraction":"NONE","scope":"UNCHANGED","confidentialityImpact":"LOW","integrityImpact":"NONE","availabilityImpact":"NONE","baseScore":5.3,"baseSeverity":"MEDIUM"},"exploitabilityScore":3.9,"impactScore":1.4}],"cvssMetricV2":[{"source":"cna@vuldb.com","type":"Secondary","cvssData":{"version":"2.0","vectorString":"AV:N\/AC:L\/Au:N\/C:P\/I:N\/A:N","accessVector":"NETWORK","accessComplexity":"LOW","authentication":"NONE","confidentialityImpact":"PARTIAL","integrityImpact":"NONE","availabilityImpact":"NONE","baseScore":5.0},"baseSeverity":"MEDIUM","exploitabilityScore":10.0,"impactScore":2.9,"acInsufInfo":false,"obtainAllPrivilege":false,"obtainUserPrivilege":false,"obtainOtherPrivilege":false,"userInteractionRequired":false}]},"weaknesses":[{"source":"cna@vuldb.com","type":"Primary","description":[{"lang":"en","value":"CWE-266"},{"lang":"en","value":"CWE-285"}]}],"references":[{"url":"https:\/\/github.com\/h0e4a0r1t\/h0e4a0r1t.github.io\/blob\/master\/2024\/HYO%3BY)v%3B4%5C)jLCjp\/Altenergy%20Power%20Control%20Software%20Information%20Disclosure%20Vulnerability_database.pdf","source":"cna@vuldb.com"},{"url":"https:\/\/vuldb.com\/?ctiid.284915","source":"cna@vuldb.com"},{"url":"https:\/\/vuldb.com\/?id.284915","source":"cna@vuldb.com"},{"url":"https:\/\/vuldb.com\/?submit.439804","source":"cna@vuldb.com"}]}}]}